// backupos-pbs is the BackupOS PBS protocol service.
//
// Architecture:
//   - HTTPS server on port 8007 (configurable)
//   - Reads cert/key generated by the Node service
//   - Reads/writes the same SQLite database as the Node service
//   - Runs alongside backupos.service as a separate systemd unit
//
// In M4b-go-scaffolding, this binary serves only /api2/json/version
// and returns 501 for /api2/json/backup and /api2/json/reader. The
// upgrade handshake, auth, and session management land in subsequent PRs.
package main

import (
	"context"
	"crypto/tls"
	"errors"
	"flag"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/handlers"
)

// Build-time variables, set via -ldflags during go build.
// These default to dev-friendly values; production deploys override them.
var (
	versionString = "4.0.0"
	releaseString = "1"
	repoIDString  = "backupos"
)

func main() {
	var (
		bind     = flag.String("bind", "0.0.0.0:8007", "address:port to listen on")
		certPath = flag.String("cert", "/var/lib/backupos/pbs/cert.pem", "TLS certificate path")
		keyPath  = flag.String("key", "/var/lib/backupos/pbs/key.pem", "TLS private key path")
		dbPath   = flag.String("db", "/var/lib/backupos/backupos.db", "SQLite database path (unused in scaffolding)")
		pbsRoot  = flag.String("pbs-root", "/var/lib/backupos/pbs", "root directory for PBS datastore data (unused in scaffolding)")
	)
	flag.Parse()

	// Suppress unused-variable warnings in scaffolding. These flags will be
	// used by the auth, upgrade, and chunk-store code in subsequent PRs.
	_ = dbPath
	_ = pbsRoot

	logger := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	logger.Info("starting backupos-pbs",
		"version", versionString,
		"release", releaseString,
		"bind", *bind,
	)

	cert, err := tls.LoadX509KeyPair(*certPath, *keyPath)
	if err != nil {
		logger.Error("failed to load TLS cert", "error", err, "cert", *certPath, "key", *keyPath)
		os.Exit(1)
	}

	versionHandler := handlers.NewVersionHandler(handlers.VersionInfo{
		Version: versionString,
		Release: releaseString,
		RepoID:  repoIDString,
	})

	mux := http.NewServeMux()
	mux.HandleFunc("/api2/json/version", versionHandler.ServeHTTP)
	mux.HandleFunc("/api2/json/backup", stub501("backup"))
	mux.HandleFunc("/api2/json/reader", stub501("reader"))
	mux.HandleFunc("/", notFound)

	server := &http.Server{
		Addr:    *bind,
		Handler: mux,
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
			// HTTP/2 ALPN deliberately disabled. PBS protocol uses HTTP/1.1
			// with Upgrade: proxmox-backup-protocol-v1 — not h2c, not h2 ALPN.
			// The upgrade handler lands in M4b-go-upgrade.
			NextProtos: []string{"http/1.1"},
		},
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		sig := <-sigCh
		logger.Info("received signal, shutting down", "signal", sig)

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(ctx); err != nil {
			logger.Error("graceful shutdown failed", "error", err)
		}
	}()

	logger.Info("listening", "bind", *bind)
	err = server.ListenAndServeTLS("", "")
	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("server failed", "error", err)
		os.Exit(1)
	}
	logger.Info("backupos-pbs stopped")
}

func stub501(kind string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		slog.Info("501 stub hit",
			"kind", kind,
			"method", r.Method,
			"path", r.URL.Path,
			"remote", r.RemoteAddr,
		)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotImplemented)
		_, _ = w.Write([]byte(`{"error":"PBS protocol ` + kind + ` endpoint pending — handler lands in M4b-go-upgrade / M4c-go"}`))
	}
}

func notFound(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusNotFound)
	_, _ = w.Write([]byte(`{"error":"not found"}`))
}
