// backupos-pbs is the BackupOS PBS protocol service.
//
// Architecture:
//   - HTTPS server on port 8007 (configurable)
//   - Reads cert/key generated by the Node service
//   - Reads/writes the same SQLite database as the Node service
//   - Runs alongside backupos.service as a separate systemd unit
//
// Endpoints:
//   - GET  /api2/json/version    unauthenticated, 200 JSON
//   - any  /api2/json/backup     401 without valid auth; with auth: upgrade handshake → H2 streams
//   - GET  /api2/json/reader     inline auth; reader upgrade handshake → H2 streams (M5a)
//
// Over the H2 connection:
//   - POST /blob    write opaque blob atomically to snapshot directory (200)
//   - POST /finish  mark session finished + fsync snapshot dir (200)
//   - any other     501 stub (M4c-go-fixed-index, dynamic-index, chunk-upload follow)
package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"flag"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/auth"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/blob"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/datastore"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/db"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/dynamicappend"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/dynamicchunk"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/dynamicclose"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/dynamicindex"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/finish"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/fixedappend"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/fixedchunk"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/fixedclose"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/fixedindex"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/download"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/gcadmin"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/gcrun"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/gcsched"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/gctask"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/handlers"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/readchunk"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/readerupgrade"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/session"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/sessionreaper"
	"github.com/dariusvorster/backupos/services/backupos-pbs/internal/upgrade"
)

// Build-time variables, set via -ldflags during go build.
var (
	versionString = "4.0.0"
	releaseString = "1"
	repoIDString  = "backupos"
)

func main() {
	var (
		bind     = flag.String("bind", "0.0.0.0:8007", "address:port to listen on")
		certPath = flag.String("cert", "/var/lib/backupos/pbs/cert.pem", "TLS certificate path")
		keyPath  = flag.String("key", "/var/lib/backupos/pbs/key.pem", "TLS private key path")
		dbPath   = flag.String("db", "/var/lib/backupos/backupos.db", "SQLite database path")
		pbsRoot  = flag.String("pbs-root", "/var/lib/backupos/pbs", "root directory for PBS datastore data (unused in this PR)")
	)
	flag.Parse()

	_ = pbsRoot // not used in this PR

	logger := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	logger.Info("starting backupos-pbs",
		"version", versionString,
		"release", releaseString,
		"bind", *bind,
	)

	// Open the SQLite database (read+write, WAL mode handled by Node side).
	database, err := db.Open(*dbPath)
	if err != nil {
		logger.Error("failed to open database", "error", err, "path", *dbPath)
		os.Exit(1)
	}
	defer func() { _ = database.Close() }()
	logger.Info("database opened", "path", *dbPath)

	validator := auth.NewValidator(database)
	datastoreLookup := datastore.NewLookup(database)
	sessionStore := session.NewStore(database)
	upgradeHandler := upgrade.NewHandler(
		datastoreLookup,
		sessionStore,
		blob.NewHandler(),
		finish.NewHandler(sessionStore),
		fixedindex.NewHandler(),
		fixedchunk.NewHandler(),
		fixedappend.NewHandler(),
		fixedclose.NewHandler(),
		dynamicindex.NewHandler(),
		dynamicchunk.NewHandler(),
		dynamicappend.NewHandler(),
		dynamicclose.NewHandler(),
		upgrade.StubStreamHandler(),
	)

	cert, err := tls.LoadX509KeyPair(*certPath, *keyPath)
	if err != nil {
		logger.Error("failed to load TLS cert", "error", err, "cert", *certPath, "key", *keyPath)
		os.Exit(1)
	}

	versionHandler := handlers.NewVersionHandler(handlers.VersionInfo{
		Version: versionString,
		Release: releaseString,
		RepoID:  repoIDString,
	})

	readerHandler := readerupgrade.NewHandler(
		validator,
		datastoreLookup,
		download.NewHandler(),
		readchunk.NewHandler(),
	)

	datastoreRoots := make(map[string]string)
	if allDS, err := datastoreLookup.All(); err != nil {
		logger.Warn("could not load datastores for GC tracker hydration", "error", err)
	} else {
		for _, ds := range allDS {
			datastoreRoots[ds.ID] = ds.Path
		}
	}
	gcTracker := gctask.NewTracker(gctask.FilePersister{}, datastoreRoots)
	oldestActiveWriter := gcrun.OldestActiveWriterFunc(func(ctx context.Context) (time.Time, error) {
		return sessionStore.OldestActiveStartedAt(ctx)
	})
	gcAdminHandler := gcadmin.NewHandler(datastoreLookup, gcTracker, oldestActiveWriter)
	gcScheduler := gcsched.New(datastoreLookup, gcTracker, oldestActiveWriter, 0)

	mux := http.NewServeMux()
	mux.HandleFunc("/api2/json/version", versionHandler.ServeHTTP)
	mux.HandleFunc("/api2/json/backup", requireAuth(validator, upgradeHandler.ServeHTTP))
	mux.HandleFunc("/api2/json/reader", readerHandler.ServeHTTP)
	mux.HandleFunc("/api2/json/admin/datastore/", requireAuth(validator,
		func(w http.ResponseWriter, r *http.Request) {
			if !strings.HasSuffix(r.URL.Path, "/gc") {
				http.NotFound(w, r)
				return
			}
			gcAdminHandler.ServeHTTP(w, r)
		},
	))
	mux.HandleFunc("/", notFound)

	// serverCtx is cancelled on SIGINT/SIGTERM so background goroutines
	// (reaper, future cron jobs) stop cleanly alongside the HTTP server.
	serverCtx, serverCancel := context.WithCancel(context.Background())
	defer serverCancel()

	reaper := sessionreaper.New(database, 0, 0)
	go reaper.Run(serverCtx)
	go gcScheduler.Run(serverCtx)

	server := &http.Server{
		Addr:    *bind,
		Handler: mux,
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
			// HTTP/2 ALPN deliberately disabled. PBS protocol uses HTTP/1.1
			// with Upgrade: proxmox-backup-protocol-v1 — not h2c, not h2 ALPN.
			// The upgrade handler lands in M4b-go-upgrade.
			NextProtos: []string{"http/1.1"},
		},
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		sig := <-sigCh
		logger.Info("received signal, shutting down", "signal", sig)
		serverCancel() // stop background goroutines
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(ctx); err != nil {
			logger.Error("graceful shutdown failed", "error", err)
		}
	}()

	logger.Info("listening", "bind", *bind)
	err = server.ListenAndServeTLS("", "")
	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("server failed", "error", err)
		os.Exit(1)
	}
	logger.Info("backupos-pbs stopped")
}

// requireAuth wraps a handler with PBS token authentication.
//
// If the Authorization header is missing or invalid, returns 401.
// If the token is valid, attaches the Identity to the request context
// (via auth.WithIdentity) and calls the wrapped handler.
func requireAuth(v *auth.Validator, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		authHeader := r.Header.Get("Authorization")
		if authHeader == "" {
			writeAuthError(w, "missing Authorization header")
			return
		}

		parsed, err := auth.ParseAuthHeader(authHeader)
		if err != nil {
			writeAuthError(w, "malformed Authorization header")
			return
		}

		identity, err := v.Validate(parsed)
		if err != nil {
			// Log the actual error for diagnostics, but return a generic
			// 401 to the caller. We don't want to leak whether the
			// token exists or just had a wrong secret.
			slog.Info("auth failed",
				"reason", err.Error(),
				"user", parsed.User,
				"realm", parsed.Realm,
				"token_name", parsed.TokenName,
				"remote", r.RemoteAddr,
			)
			writeAuthError(w, "invalid credentials")
			return
		}

		slog.Info("auth ok",
			"token_id", identity.TokenID,
			"user", identity.User,
			"realm", identity.Realm,
			"token_name", identity.TokenName,
			"path", r.URL.Path,
			"method", r.Method,
		)

		ctx := auth.WithIdentity(r.Context(), identity)
		next(w, r.WithContext(ctx))
	}
}

func writeAuthError(w http.ResponseWriter, reason string) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", `PBSAPIToken realm="backupos"`)
	w.WriteHeader(http.StatusUnauthorized)
	resp := map[string]string{"error": reason}
	_ = json.NewEncoder(w).Encode(resp)
}

func notFound(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusNotFound)
	resp := map[string]string{"error": "not found"}
	_ = json.NewEncoder(w).Encode(resp)
}
