// backupos-xcp is the BackupOS XCP-ng protocol service.
//
// Architecture:
//   - HTTPS server on port 8009 (configurable)
//   - Reads cert/key generated by the Node service
//   - Runs alongside backupos.service as a separate systemd unit
//
// Endpoints:
//   - GET /api2/json/version  unauthenticated, 200 JSON
package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"flag"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/dariusvorster/backupos/services/backupos-xcp/internal/xapi"
)

// Build-time variables, set via -ldflags during go build.
var (
	versionString = "0.1.0"
	releaseString = "1"
	repoIDString  = "backupos-xcp"
)

func main() {
	var (
		bind     = flag.String("bind", "0.0.0.0:8009", "address:port to listen on")
		certPath = flag.String("cert", "/var/lib/backupos/xcp/cert.pem", "TLS certificate path")
		keyPath  = flag.String("key", "/var/lib/backupos/xcp/key.pem", "TLS private key path")
		dbPath   = flag.String("db", "/var/lib/backupos/backupos.db", "SQLite database path")

		// XAPI connection flags. If xapiURL is empty, the service starts but
		// XAPI features are disabled — useful for the placeholder Phase 1 deploy.
		xapiURL      = flag.String("xapi-url", "", "XAPI pool master URL (e.g. https://192.168.69.2)")
		xapiUser     = flag.String("xapi-user", "root", "XAPI username")
		xapiPass     = flag.String("xapi-pass", "", "XAPI password (or set BACKUPOS_XCP_PASS env var)")
		xapiFP       = flag.String("xapi-cert-fingerprint", "", "XAPI host TLS cert SHA256 fingerprint (optional)")
		xapiInsecure = flag.Bool("xapi-insecure", false, "Disable TLS verification for XAPI (dev only)")
	)
	flag.Parse()

	// Password can also come from env var (preferred for systemd EnvironmentFile).
	if *xapiPass == "" {
		*xapiPass = os.Getenv("BACKUPOS_XCP_PASS")
	}

	_ = dbPath // reserved for future use

	logger := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	logger.Info("starting backupos-xcp",
		"version", versionString,
		"release", releaseString,
		"bind", *bind,
	)

	internalURL := os.Getenv("BACKUPOS_INTERNAL_URL")
	internalSecret := os.Getenv("BACKUPOS_INTERNAL_SECRET")
	if internalURL == "" || internalSecret == "" {
		slog.Warn("BACKUPOS_INTERNAL_URL or BACKUPOS_INTERNAL_SECRET not set; XCP alerts will not fire")
	} else {
		slog.Info("internal webhook configured", "url", internalURL)
	}

	cert, err := tls.LoadX509KeyPair(*certPath, *keyPath)
	if err != nil {
		logger.Error("failed to load TLS cert", "error", err, "cert", *certPath, "key", *keyPath)
		os.Exit(1)
	}

	// serverCtx is the parent context for all incoming HTTP request contexts
	// (via http.Server.BaseContext). Cancelled on SIGINT/SIGTERM so in-flight
	// requests can react to shutdown. Phase 2 will also use serverCtx to stop
	// background goroutines (XAPI session reaper, CBT chain GC scheduler).
	serverCtx, serverCancel := context.WithCancel(context.Background())
	defer serverCancel()

	var xapiClient *xapi.Client
	if *xapiURL != "" {
		cfg := xapi.Config{
			PoolMasterURL:      *xapiURL,
			Username:           *xapiUser,
			Password:           *xapiPass,
			CertFingerprint:    *xapiFP,
			InsecureSkipVerify: *xapiInsecure,
		}
		xc, err := xapi.New(cfg, logger)
		if err != nil {
			logger.Error("xapi: invalid config", "error", err)
			os.Exit(1)
		}
		if err := xc.Connect(serverCtx); err != nil {
			logger.Error("xapi: initial connect failed", "error", err)
			// Non-fatal: service still starts, but XAPI endpoints will return 503.
		} else {
			xapiClient = xc
			defer xapiClient.Close() //nolint:gocritic
		}
	} else {
		logger.Warn("xapi-url not set; XAPI endpoints will return 503")
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/api2/json/version", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("version",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		resp := map[string]string{
			"version": versionString,
			"release": releaseString,
			"repoID":  repoIDString,
		}
		_ = json.NewEncoder(w).Encode(resp)
	})
	mux.HandleFunc("/api2/json/pool", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("pool",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)

		if xapiClient == nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "xapi client not configured",
			})
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
		defer cancel()

		uuid, name, err := xapiClient.PoolName(ctx)
		if err != nil {
			slog.Error("pool query failed", "error", err)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadGateway)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": err.Error(),
			})
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]string{
			"uuid": uuid,
			"name": name,
		})
	})
	mux.HandleFunc("/api2/json/changed-blocks", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("changed-blocks",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)

		if xapiClient == nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "xapi client not configured",
			})
			return
		}

		fromUUID := r.URL.Query().Get("from")
		toUUID := r.URL.Query().Get("to")
		if fromUUID == "" || toUUID == "" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "from and to query parameters required",
			})
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
		defer cancel()

		regions, err := xapiClient.ChangedRegions(ctx, fromUUID, toUUID)
		if err != nil {
			slog.Error("changed-blocks query failed", "error", err, "from", fromUUID, "to", toUUID)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadGateway)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": err.Error(),
			})
			return
		}

		var totalBytes int64
		for _, rg := range regions {
			totalBytes += rg.Length
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"from":         fromUUID,
			"to":           toUUID,
			"block_size":   xapi.BlockSize,
			"region_count": len(regions),
			"total_bytes":  totalBytes,
			"regions":      regions,
		})
	})
	mux.HandleFunc("/", notFound)

	server := &http.Server{
		Addr:    *bind,
		Handler: mux,
		BaseContext: func(_ net.Listener) context.Context {
			return serverCtx
		},
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
			NextProtos:   []string{"http/1.1"},
		},
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		sig := <-sigCh
		logger.Info("received signal, shutting down", "signal", sig)
		serverCancel()
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(ctx); err != nil {
			logger.Error("graceful shutdown failed", "error", err)
		}
	}()

	logger.Info("listening", "bind", *bind)
	err = server.ListenAndServeTLS("", "")
	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("server failed", "error", err)
		os.Exit(1)
	}
	logger.Info("backupos-xcp stopped")
}

func notFound(w http.ResponseWriter, r *http.Request) {
	slog.Info("404",
		"method", r.Method,
		"path",   r.URL.Path,
		"query",  r.URL.RawQuery,
		"remote", r.RemoteAddr,
	)
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusNotFound)
	resp := map[string]string{"error": "not found"}
	_ = json.NewEncoder(w).Encode(resp)
}
