// backupos-xcp is the BackupOS XCP-ng protocol service.
//
// Architecture:
//   - HTTPS server on port 8009 (configurable)
//   - Reads cert/key generated by the Node service
//   - Runs alongside backupos.service as a separate systemd unit
//
// Endpoints:
//   - GET /api2/json/version  unauthenticated, 200 JSON
package main

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/dariusvorster/backupos/services/backupos-xcp/internal/nbdread"
	"github.com/dariusvorster/backupos/services/backupos-xcp/internal/xapi"
)

// Build-time variables, set via -ldflags during go build.
var (
	versionString = "0.1.0"
	releaseString = "1"
	repoIDString  = "backupos-xcp"
)

func respondJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func respondJSONError(w http.ResponseWriter, status int, msg string) {
	respondJSON(w, status, map[string]string{"error": msg})
}

func main() {
	var (
		bind     = flag.String("bind", "0.0.0.0:8009", "address:port to listen on")
		certPath = flag.String("cert", "/var/lib/backupos/xcp/cert.pem", "TLS certificate path")
		keyPath  = flag.String("key", "/var/lib/backupos/xcp/key.pem", "TLS private key path")
		dbPath   = flag.String("db", "/var/lib/backupos/backupos.db", "SQLite database path")

		// XAPI connection flags. If xapiURL is empty, the service starts but
		// XAPI features are disabled — useful for the placeholder Phase 1 deploy.
		xapiURL      = flag.String("xapi-url", "", "XAPI pool master URL (e.g. https://192.168.69.2)")
		xapiUser     = flag.String("xapi-user", "root", "XAPI username")
		xapiPass     = flag.String("xapi-pass", "", "XAPI password (or set BACKUPOS_XCP_PASS env var)")
		xapiFP       = flag.String("xapi-cert-fingerprint", "", "XAPI host TLS cert SHA256 fingerprint (optional)")
		xapiInsecure = flag.Bool("xapi-insecure", false, "Disable TLS verification for XAPI (dev only)")
		readOutputDir = flag.String("read-output-dir", "/var/lib/backupos/xcp-reads",
			"directory under which /api2/json/snapshot/{uuid}/read can write files")
	)
	flag.Parse()

	// Password can also come from env var (preferred for systemd EnvironmentFile).
	if *xapiPass == "" {
		*xapiPass = os.Getenv("BACKUPOS_XCP_PASS")
	}

	_ = dbPath // reserved for future use

	logger := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	slog.SetDefault(logger)

	absReadDir, readDirErr := filepath.Abs(*readOutputDir)
	if readDirErr != nil {
		logger.Error("resolve read-output-dir", "error", readDirErr)
		os.Exit(1)
	}
	readOutputDirResolved := filepath.Clean(absReadDir)
	if readDirErr = os.MkdirAll(readOutputDirResolved, 0o755); readDirErr != nil {
		logger.Error("create read-output-dir", "error", readDirErr)
		os.Exit(1)
	}

	logger.Info("starting backupos-xcp",
		"version", versionString,
		"release", releaseString,
		"bind", *bind,
	)

	internalURL := os.Getenv("BACKUPOS_INTERNAL_URL")
	internalSecret := os.Getenv("BACKUPOS_INTERNAL_SECRET")
	if internalURL == "" || internalSecret == "" {
		slog.Warn("BACKUPOS_INTERNAL_URL or BACKUPOS_INTERNAL_SECRET not set; XCP alerts will not fire")
	} else {
		slog.Info("internal webhook configured", "url", internalURL)
	}

	cert, err := tls.LoadX509KeyPair(*certPath, *keyPath)
	if err != nil {
		logger.Error("failed to load TLS cert", "error", err, "cert", *certPath, "key", *keyPath)
		os.Exit(1)
	}

	// serverCtx is the parent context for all incoming HTTP request contexts
	// (via http.Server.BaseContext). Cancelled on SIGINT/SIGTERM so in-flight
	// requests can react to shutdown. Phase 2 will also use serverCtx to stop
	// background goroutines (XAPI session reaper, CBT chain GC scheduler).
	serverCtx, serverCancel := context.WithCancel(context.Background())
	defer serverCancel()

	var xapiClient *xapi.Client
	if *xapiURL != "" {
		cfg := xapi.Config{
			PoolMasterURL:      *xapiURL,
			Username:           *xapiUser,
			Password:           *xapiPass,
			CertFingerprint:    *xapiFP,
			InsecureSkipVerify: *xapiInsecure,
		}
		xc, err := xapi.New(cfg, logger)
		if err != nil {
			logger.Error("xapi: invalid config", "error", err)
			os.Exit(1)
		}
		if err := xc.Connect(serverCtx); err != nil {
			logger.Error("xapi: initial connect failed", "error", err)
			// Non-fatal: service still starts, but XAPI endpoints will return 503.
		} else {
			xapiClient = xc
			defer xapiClient.Close() //nolint:gocritic
		}
	} else {
		logger.Warn("xapi-url not set; XAPI endpoints will return 503")
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/api2/json/version", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("version",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		resp := map[string]string{
			"version": versionString,
			"release": releaseString,
			"repoID":  repoIDString,
		}
		_ = json.NewEncoder(w).Encode(resp)
	})
	mux.HandleFunc("/api2/json/pool", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("pool",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)

		if xapiClient == nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "xapi client not configured",
			})
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
		defer cancel()

		uuid, name, err := xapiClient.PoolName(ctx)
		if err != nil {
			slog.Error("pool query failed", "error", err)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadGateway)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": err.Error(),
			})
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]string{
			"uuid": uuid,
			"name": name,
		})
	})
	mux.HandleFunc("/api2/json/changed-blocks", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("changed-blocks",
			"method", r.Method,
			"path",   r.URL.Path,
			"remote", r.RemoteAddr,
		)

		if xapiClient == nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "xapi client not configured",
			})
			return
		}

		fromUUID := r.URL.Query().Get("from")
		toUUID := r.URL.Query().Get("to")
		if fromUUID == "" || toUUID == "" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": "from and to query parameters required",
			})
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
		defer cancel()

		regions, err := xapiClient.ChangedRegions(ctx, fromUUID, toUUID)
		if err != nil {
			slog.Error("changed-blocks query failed", "error", err, "from", fromUUID, "to", toUUID)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadGateway)
			_ = json.NewEncoder(w).Encode(map[string]string{
				"error": err.Error(),
			})
			return
		}

		var totalBytes int64
		for _, rg := range regions {
			totalBytes += rg.Length
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"from":         fromUUID,
			"to":           toUUID,
			"block_size":   xapi.BlockSize,
			"region_count": len(regions),
			"total_bytes":  totalBytes,
			"regions":      regions,
		})
	})
	mux.HandleFunc("/api2/json/snapshot", func(w http.ResponseWriter, r *http.Request) {
		slog.Info("snapshot",
			"method", r.Method,
			"path", r.URL.Path,
			"remote", r.RemoteAddr,
		)

		if r.Method != http.MethodPost {
			w.Header().Set("Allow", "POST")
			http.Error(w, `{"error":"method not allowed"}`, http.StatusMethodNotAllowed)
			return
		}
		if xapiClient == nil {
			respondJSONError(w, http.StatusServiceUnavailable, "xapi client not configured")
			return
		}

		var body struct {
			SourceUUID string `json:"source_uuid"`
			NameLabel  string `json:"name_label"`
		}
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			respondJSONError(w, http.StatusBadRequest, "invalid JSON body: "+err.Error())
			return
		}
		if body.SourceUUID == "" {
			respondJSONError(w, http.StatusBadRequest, "source_uuid required")
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
		defer cancel()

		info, err := xapiClient.Snapshot(ctx, body.SourceUUID, body.NameLabel)
		if err != nil {
			slog.Error("snapshot failed", "error", err, "source_uuid", body.SourceUUID)
			respondJSONError(w, http.StatusBadGateway, err.Error())
			return
		}

		respondJSON(w, http.StatusOK, info)
	})
	mux.HandleFunc("/api2/json/snapshot/", func(w http.ResponseWriter, r *http.Request) {
		suffix := strings.TrimPrefix(r.URL.Path, "/api2/json/snapshot/")
		parts := strings.SplitN(suffix, "/", 2)
		uuid := parts[0]
		sub := ""
		if len(parts) == 2 {
			sub = parts[1]
		}

		switch {
		case r.Method == http.MethodDelete && sub == "":
			slog.Info("snapshot-delete", "method", r.Method, "path", r.URL.Path, "remote", r.RemoteAddr)
			if xapiClient == nil {
				respondJSONError(w, http.StatusServiceUnavailable, "xapi client not configured")
				return
			}
			if uuid == "" {
				respondJSONError(w, http.StatusBadRequest, "snapshot uuid required in path")
				return
			}
			mode := r.URL.Query().Get("mode")
			if mode == "" {
				mode = "destroy"
			}
			ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
			defer cancel()
			var err error
			switch mode {
			case "destroy":
				err = xapiClient.DestroySnapshot(ctx, uuid)
			case "data_destroy":
				err = xapiClient.DataDestroySnapshot(ctx, uuid)
			default:
				respondJSONError(w, http.StatusBadRequest, "mode must be 'destroy' or 'data_destroy'")
				return
			}
			if err != nil {
				slog.Error("snapshot delete failed", "error", err, "uuid", uuid, "mode", mode)
				respondJSONError(w, http.StatusBadGateway, err.Error())
				return
			}
			respondJSON(w, http.StatusOK, map[string]any{"uuid": uuid, "mode": mode, "status": "ok"})

		case r.Method == http.MethodGet && sub == "nbd-info":
			slog.Info("snapshot-nbd-info", "method", r.Method, "path", r.URL.Path, "remote", r.RemoteAddr)
			if xapiClient == nil {
				respondJSONError(w, http.StatusServiceUnavailable, "xapi client not configured")
				return
			}
			if uuid == "" {
				respondJSONError(w, http.StatusBadRequest, "snapshot uuid required in path")
				return
			}
			ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
			defer cancel()
			infos, err := xapiClient.SnapshotNBDInfo(ctx, uuid)
			if err != nil {
				slog.Error("nbd-info query failed", "error", err, "uuid", uuid)
				respondJSONError(w, http.StatusBadGateway, err.Error())
				return
			}
			type sanitized struct {
				ExportName      string `json:"export_name"`
				Address         string `json:"address"`
				Port            int    `json:"port"`
				Subject         string `json:"subject"`
				CertFingerprint string `json:"cert_fingerprint_sha256"`
			}
			san := make([]sanitized, len(infos))
			for i, info := range infos {
				sum := sha256.Sum256([]byte(info.CertPEM))
				san[i] = sanitized{
					ExportName:      info.ExportName,
					Address:         info.Address,
					Port:            info.Port,
					Subject:         info.Subject,
					CertFingerprint: hex.EncodeToString(sum[:]),
				}
			}
			respondJSON(w, http.StatusOK, map[string]any{"uuid": uuid, "options": san})

		case r.Method == http.MethodPost && sub == "read":
			slog.Info("snapshot-read", "method", r.Method, "path", r.URL.Path, "remote", r.RemoteAddr)
			if xapiClient == nil {
				respondJSONError(w, http.StatusServiceUnavailable, "xapi client not configured")
				return
			}
			if uuid == "" {
				respondJSONError(w, http.StatusBadRequest, "snapshot uuid required in path")
				return
			}
			var body struct {
				OutputPath string          `json:"output_path"`
				Regions    []nbdread.Region `json:"regions"`
			}
			if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
				respondJSONError(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
				return
			}
			if body.OutputPath == "" {
				respondJSONError(w, http.StatusBadRequest, "output_path required")
				return
			}
			if len(body.Regions) == 0 {
				respondJSONError(w, http.StatusBadRequest, "regions required (at least one)")
				return
			}
			if !strings.HasPrefix(filepath.Clean(body.OutputPath), readOutputDirResolved) {
				respondJSONError(w, http.StatusBadRequest, "output_path must be under "+readOutputDirResolved)
				return
			}
			nbdCtx, nbdCancel := context.WithTimeout(r.Context(), 30*time.Second)
			defer nbdCancel()
			infos, err := xapiClient.SnapshotNBDInfo(nbdCtx, uuid)
			if err != nil {
				respondJSONError(w, http.StatusBadGateway, "get_nbd_info: "+err.Error())
				return
			}
			if len(infos) == 0 {
				respondJSONError(w, http.StatusBadGateway,
					"no NBD options available for this snapshot — is NBD enabled on a network reaching this host's SR?")
				return
			}
			chosen := infos[0]
			f, err := os.Create(body.OutputPath)
			if err != nil {
				respondJSONError(w, http.StatusInternalServerError, "create output: "+err.Error())
				return
			}
			defer f.Close()
			readCtx, readCancel := context.WithTimeout(r.Context(), 10*time.Minute)
			defer readCancel()
			res, err := nbdread.ReadRegions(readCtx, nbdread.Connection{
				Address:    chosen.Address,
				Port:       chosen.Port,
				ExportName: chosen.ExportName,
				CertPEM:    chosen.CertPEM,
				Subject:    chosen.Subject,
			}, body.Regions, f)
			if err != nil {
				slog.Error("nbd read failed", "error", err, "uuid", uuid)
				respondJSONError(w, http.StatusBadGateway, err.Error())
				return
			}
			respondJSON(w, http.StatusOK, map[string]any{
				"uuid":         uuid,
				"output_path":  body.OutputPath,
				"bytes_read":   res.BytesRead,
				"region_count": res.RegionCount,
				"sha256":       res.SHA256Hex,
				"duration_ms":  res.DurationMS,
			})

		default:
			w.Header().Set("Allow", "DELETE, GET, POST")
			respondJSONError(w, http.StatusMethodNotAllowed, "method not allowed")
		}
	})
	mux.HandleFunc("/", notFound)

	server := &http.Server{
		Addr:    *bind,
		Handler: mux,
		BaseContext: func(_ net.Listener) context.Context {
			return serverCtx
		},
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
			MinVersion:   tls.VersionTLS12,
			NextProtos:   []string{"http/1.1"},
		},
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		sigCh := make(chan os.Signal, 1)
		signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
		sig := <-sigCh
		logger.Info("received signal, shutting down", "signal", sig)
		serverCancel()
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := server.Shutdown(ctx); err != nil {
			logger.Error("graceful shutdown failed", "error", err)
		}
	}()

	logger.Info("listening", "bind", *bind)
	err = server.ListenAndServeTLS("", "")
	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("server failed", "error", err)
		os.Exit(1)
	}
	logger.Info("backupos-xcp stopped")
}

func notFound(w http.ResponseWriter, r *http.Request) {
	slog.Info("404",
		"method", r.Method,
		"path",   r.URL.Path,
		"query",  r.URL.RawQuery,
		"remote", r.RemoteAddr,
	)
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusNotFound)
	resp := map[string]string{"error": "not found"}
	_ = json.NewEncoder(w).Encode(resp)
}
